env:
  - HUGO_VERSION="v0.29" HUGO_DEB="hugo_0.29_Linux-64bit.deb" 

before_install:
  - wget https://github.com/gohugoio/hugo/releases/download/${HUGO_VERSION}/${HUGO_DEB}
         https://github.com/gohugoio/hugo/releases/download/v0.30/hugo_0.30_Linux-64bit.deb

  - sudo dpkg -i ${HUGO_DEB}

script:
  - hugo

deploy:
  provider: s3
  access_key_id: ${AWSAccessKeyId}
  secret_access_key: ${AWSSecretKey}
  bucket: "owayss.me"
  region: "eu-west-1"
  local_dir: public
  acl: public_read
  skip_cleanup: true